version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  api:
    build:
      context: ./api
    ports:
      - 5010:5010
    depends_on:
      - db

  shiny:
    build:
      context: ./shiny
    restart: unless-stopped
    ports:
      - "3838:3838"
    depends_on:
      - db
      - api
volumes:
  data:
